/** @type {import('tailwindcss').Config} */
module.exports = {
	darkMode: 'class',
	content: [
		'./pages/**/*.{js,ts,jsx,tsx}',
		'./components/**/*.{js,ts,jsx,tsx}',
	],
	theme: {
		extend: {
			colors: {
				background: '#121212',
				overlay: 'rgba(0,0,0,0.6)',
				ui: '#4c4c4c',
				'ui-dark': '#aaaaaa',
				contrast: '#ffffff14',
				'ui-dark-hover': '#606060',
				'ui-hover': '#181818',
			},
			transitionProperty: {
				background: 'background',
				margin: 'margin',
				outline: 'outline',
			},
			typography: ({ theme }) => ({
				code: {
					css: {
						'--tw-prose-body': '#27272a',
						'--tw-prose-headings': '#18181b',
						'--tw-prose-lead': '#27272a',
						'--tw-prose-links': '#555',
						'--tw-prose-bold': '#18181b',
						'--tw-prose-counters': '#d4d4d8',
						'--tw-prose-bullets': '#d4d4d8',
						'--tw-prose-hr': '#d4d4d8',
						'--tw-prose-quotes': '#27272a',
						'--tw-prose-quote-borders': '#ffffff20',
						'--tw-prose-captions': '#3f3f46',
						'--tw-prose-code': '#18181b',
						'--tw-prose-pre-code': '#18181b',
						'--tw-prose-pre-bg': '#fff',
						'--tw-prose-th-borders': '#d4d4d8',
						'--tw-prose-td-borders': '#d4d4d8',
						'--tw-prose-invert-body': '#efefef',
						'--tw-prose-invert-headings': '#fff',
						'--tw-prose-invert-lead': '#9ca3af',
						'--tw-prose-invert-links': '#fff',
						'--tw-prose-invert-bold': '#fff',
						'--tw-prose-invert-counters': '#9ca3af',
						'--tw-prose-invert-bullets': '#4b5563',
						'--tw-prose-invert-hr': '#374151',
						'--tw-prose-invert-quotes': '#f3f4f6',
						'--tw-prose-invert-quote-borders': '#ffffff20',
						'--tw-prose-invert-captions': '#9ca3af',
						'--tw-prose-invert-code': '#fff',
						'--tw-prose-invert-pre-code': '#d1d5db',
						'--tw-prose-invert-pre-bg': '#131414',
						'--tw-prose-invert-th-borders': '#4b5563',
						'--tw-prose-invert-td-borders': '#374151',
					},
				},
			}),
		},
	},
	plugins: [
		require('@tailwindcss/typography'),
		require('tailwind-scrollbar-hide'),
	],
};
